@echo off
echo Starting AI Therapist...

echo Starting Backend...
start "AI Therapist Backend" cmd /k "cd /d %~dp0 && python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"

echo Starting Frontend...
start "AI Therapist Frontend" cmd /k "cd /d %~dp0\frontend && npm run dev"

echo Both services are starting...
echo Backend: http://localhost:8000
echo Frontend: http://localhost:3000
